title: Ikezu-Ishi
description: A feudal Japan inspired RPG based on Cairn, Into the Odd, and Block, Dodge, Parry
theme: just-the-docs

url: https://jasonkenney.github.io/Ikezu-ishi/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Set a path/url to a logo that will be displayed instead of the title
logo: "/images/ii-logo.png"
